version: '3.7'

services:

  labelme:
    image: labelme
    container_name: labelme
    ports:
      - $PORT:80
    volumes:
      - $IMAGES:/var/www/html/LabelMeAnnotationTool/Images
      - $ANNOTATIONS:/var/www/html/LabelMeAnnotationTool/Annotations
    env_file:
      - deploy.env